version: "3.8"

secrets:
  config.ini:
    file: ./private/config.ini
  ssl-default.crt:
    file: ./private/ssl/default.crt
  ssl-default.key:
    file: ./private/ssl/default.key
  ssl-milo.king.com.crt:
    file: ./private/ssl/milo.king.com.crt
  ssl-milo.king.com.key:
    file: ./private/ssl/milo.king.com.key

volumes:
  postgres-data:

services:
  adminer:
    image: docker.io/library/adminer
    ports:
      - 127.0.0.1:8084:8080

  bind9:
    build:
      context: ./bind9
      secrets:
        - config.ini

  cotr-server:
    build: ./cotr-server
    secrets:
      - config.ini
    environment:
      CONFIG_PATH: /run/secrets/config.ini
      POSTGRES_HOST: postgres
      POSTGRES_USER: crash
      POSTGRES_PASSWORD: crash3ID6NW
      POSTGRES_DATABASE: crash
    depends_on:
      - postgres

  discord-app:
    build: ./discord-app
    secrets:
      - config.ini
    environment:
      CONFIG_PATH: /run/secrets/config.ini
      COTR_SERVER_HOST: cotr-server

  dns-over-http:
     image: docker.io/satishweb/doh-server
     environment:
      UPSTREAM_DNS_SERVER: 'udp:bind9:53'
      DOH_HTTP_PREFIX: '/dns-query'

  nginx:
    build: ./nginx
    secrets:
      - ssl-default.crt
      - ssl-default.key
      - ssl-milo.king.com.crt
      - ssl-milo.king.com.key
    ports:
      - 80:80
      - 443:443

  postgres:
    image: docker.io/library/postgres
    shm_size: 256MB
    environment:
      POSTGRES_USER: crash
      POSTGRES_PASSWORD: crash3ID6NW
      POSTGRES_DATABASE: crash
    volumes:
      - postgres-data:/var/lib/postgresql/data
